### ISSUE TITLE
Google_services.json file is missing

### ISSUE THREAD

**Issue by lucifer0987** [UdacityAndroidBasicsScholarship/design-villa#64]
please reply asap...
due to this, I am not getting a successful build.

**Comment by amy6** [comment]
Hi @lucifer0987 please go through the pinned items in the channel. You can find the instructions to add `google_services.json` file there. 
For debugging errors like these, you can consider asking in any of the slack channels so that you'll get quicker replies. Feel free to reach out to us for any further queries. :v: Good luck :+1:
